#config_version=6

switches:
  # Core switches
  s_flipper_left:
    number:
  s_flipper_right:
    number:
  s_start:
    number:
    tags: start
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger:
    number:
  # Main Lanes
  s_orbit_left:
    number:
  s_center_ramp:
    number:
  s_orbit_right:
    number:
